import { IInboxData } from "@/interfaces/apis/inbox";

export const inboxDummy: IInboxData[] = [
  {
    id: 1,
    subject: "109220-Naturalization",
    senderUserName: "Cameron Phillips",
    receiverUserName: "Agent",
    lastMessage: "Please check this out!",
    sentDate: new Date().toISOString(),
    isRead: false,
  },
  {
    id: 2,
    subject:
      "Jeannette Moraima Guaman Chamba (Hutto I-589) [ Hutto Follow Up - Brief Service ]",
    senderUserName: "Ellen",
    receiverUserName: "Agent",
    lastMessage: "Hey, please read.",
    sentDate: new Date().toISOString(),
    isRead: true,
  },
  {
    id: 3,
    subject: "8405-Diana SALAZAR MUNGUIA",
    senderUserName: "Cameron Phillips",
    receiverUserName: "Agent",
    lastMessage:
      "I understand your initial concerns and thats very valid, Elizabeth. But you need blablablabla blablabla blablabla",
    sentDate: new Date().toISOString(),
    isRead: true,
  },
  {
    id: 4,
    subject: "FastVisa Support",
    senderUserName: null,
    receiverUserName: "Agent",
    lastMessage: "Hey there! Welcome to your inbox.",
    sentDate: new Date().toISOString(),
    isRead: true,
  },
  {
    id: 4,
    subject: "FastVisa Support",
    senderUserName: null,
    receiverUserName: "Agent",
    lastMessage: "Hey there! Welcome to your inbox.",
    sentDate: new Date().toISOString(),
    isRead: true,
  },
  {
    id: 4,
    subject: "FastVisa Support",
    senderUserName: null,
    receiverUserName: "Agent",
    lastMessage: "Hey there! Welcome to your inbox.",
    sentDate: new Date().toISOString(),
    isRead: true,
  },
  {
    id: 4,
    subject: "FastVisa Support",
    senderUserName: null,
    receiverUserName: "Agent",
    lastMessage: "Hey there! Welcome to your inbox.",
    sentDate: new Date().toISOString(),
    isRead: true,
  },
  {
    id: 4,
    subject: "FastVisa Support",
    senderUserName: null,
    receiverUserName: "Agent",
    lastMessage: "Hey there! Welcome to your inbox.",
    sentDate: new Date().toISOString(),
    isRead: true,
  },
  {
    id: 4,
    subject: "FastVisa Support",
    senderUserName: null,
    receiverUserName: "Agent",
    lastMessage: "Hey there! Welcome to your inbox.",
    sentDate: new Date().toISOString(),
    isRead: true,
  },
];
